version: "3.8"

services:

  vault-server:
    container_name: vault-server
    image: index.docker.io/hashicorp/vault:1.9.0
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
